zuul:
  routes:
    user-info-service:
      path: /user-info/**
      service-id: user-info-service
    movie-info-service:
      path: /movie-info/**
      service-id: movie-info-service
    tvseries-info-service:
      path: /tvseries-info/**
      service-id: tvseries-info-service
    payment-info-service:
      path: /payment-info/**
      service-id: payment-info-service
    authorization-server:
      path: /auth/**
      service-id: authorization-server
  host:
    socket-timeout-millis: 120000
    connect-timeout-millis: 120000
  sensitive-headers: Cookie, Set-Cookie, Access-Control-Allow-Credentials, Access-Control-Allow-Origin


discovery:
  server:
    port: 8070
    hostName: 18.119.40.220

eureka:
  client:
    serviceUrl:
       defaultZone: 'http://${discovery.server.hostName}:${discovery.server.port}/eureka'
    region: us-east-2
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    ip-address: 18.119.40.220
    hostname: 18.119.40.220
    non-secure-port: 8075


#120 seconds

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000


ribbon:
  ReadTimeout: 120000
  connection-timeout: 120000
  eureka:
    enabled: true
    
logging:
  file:
    name: '/home/ubuntu/voyage-logs/gateway.log'
  level:
    root: info

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'

spring:
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*

local:
  log:
    dir: '/home/ubuntu/voyage-logs'
amazon:
  bucket:
    name: voyage-logs
  access-key: AKIAZHUKXDCDA6U4U2MP
  secret-key: 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
