zuul:
  routes:
    user-info-service:
      path: /user-info/**
      service-id: user-info-service
    movie-info-service:
      path: /movie-info/**
      service-id: movie-info-service
    tvseries-info-service:
      path: /tvseries-info/**
      service-id: tvseries-info-service
    payment-info-service:
      path: /payment-info/**
      service-id: payment-info-service
    authorization-server:
      path: /auth/**
      service-id: authorization-server
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitive-headers: Cookie, Set-Cookie, Access-Control-Allow-Credentials, Access-Control-Allow-Origin


discovery:
  server:
    port: 8070
    hostName: 127.0.0.1

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${discovery.server.hostName}:${discovery.server.port}/eureka'

#60 seconds

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000


ribbon:
  ReadTimeout: 60000
  connection-timeout: 60000
  eureka:
    enabled: true
    
logging:
  file:
    name: 'D:/Spring Boot Project/jibra-logs/common.log'
  level:
    root: info


management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - '*'